Transform: AWS::Serverless-2016-10-31

Resources:
  DDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: title
        Type: String
      TableName: CFNDDBAddItemSampleTable
  DDBTable2:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: title
        Type: String
      TableName: CFNDDBAddItemSampleTable2
  AddItemToDDB:
    Type: Custom::CFNDDBAddItem
    Properties:
      ServiceToken: !ImportValue CFNDDBAddItem
      TableName: !Ref DDBTable
      Item: >
        {
            "year" : 2013,
            "title" : "Turn It Down, Or Else!",
            "info" : {
                "directors" : [
                    "Alice Smith",
                    "Bob Jones"
                ],
                "release_date" : "2013-01-18T00:00:00Z",
                "rating" : 6.2,
                "genres" : [
                    "Comedy",
                    "Drama"
                ],
                "image_url" : "http://ia.media-imdb.com/images/N/O9ERWAU7FS797AJ7LU8HN09AMUP908RLlo5JF90EWR7LJKQ7@@._V1_SX400_.jpg",
                "plot" : "A rock band plays their music at high volumes, annoying the neighbors.",
                "rank" : 11,
                "running_time_secs" : 5215,
                "actors" : [
                    "David Matthewman",
                    "Ann Thomas",
                    "Jonathan G. Neff"
              ]
            }
        }